language: node_js
node_js:
  - "node"
addons:
  sauce_connect:
    no_ssl_bump_domains: "all"
after_script:
  - "npm install -g coveralls"
  - "cat coverage/lcov.dat | coveralls"
after_success:
  - "npm install -g codeclimate-test-reporter"
  - "codeclimate-test-reporter < coverage/lcov.dat"
