nodeLinker: node-modules

plugins:
  - checksum: 0c15f3682f03dfdd8bbf8497b3fdaa55938167d8909356804ab90898eb816dc911f9220c536d03fe7a028a48622afe58aaf6ff382cd20dad11dc527d85fcf21b
    path: .yarn/plugins/plugin-rsp-duplicates.cjs
    spec: "https://raw.githubusercontent.com/adobe/react-spectrum/refs/heads/main/lib/yarn-plugin-rsp-duplicates.js"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
