import keyMirror from 'keymirror';

export default keyMirror({
  SET_CONFIG: null,
  VALIDATE: null,

  SET_SHOW_SPECIFIC_ELEMENTS_FILTER: null,
  SET_SHOW_ELEMENT_PROPERTIES_FILTER: null,

  SET_ELEMENT_SELECTOR: null,

  ADD_ELEMENT_PROPERTY: null,
  REMOVE_ELEMENT_PROPERTY: null,
  EDIT_ELEMENT_PROPERTY: null,

  SET_DELAY_LINK_ACTIVATION: null,

  SET_BUBBLE_FIRE_IF_PARENT: null,
  SET_BUBBLE_FIRE_IF_CHILD_FIRED: null,
  SET_BUBBLE_STOP: null
});
